# This is the server code for the Aurora application
# Developers: Grant Abernethy and Felix Zareie-Vaux

server <- function(input, output, session) {
  # reportItems ========
  # A global store for outputs generated by tabs
  reportItems <- reactiveValues(
    tables = list(),
    plots = list()
  )

  # Launch tab ============================
  # This it the launch/splash page tab, when the Aurora app is first opened
  # Launch contains information to explain the app to users
  # The tab also contains a toggle to switch between user data and the example data

  fpath <- reactive({
    if (input$include_examples == TRUE) {
      examplepath
    } else {
      filepath
    }
  })

  # Toggle to switch between user data and example data
  observeEvent(input$include_examples, {
    loadprimarydata(table_mapping, fpath())
    toastr_success("Data Switched", position = "bottom-left")
  })


  # Search tab ============================
  # Used to search for samples across Data Tables
  # Get the first table selected by widget, then if there's more than 1, left_join the others, and select just the columns in the customize columns box
  # 🌱 Can we make preset searches (formerly special cases) use mutually exclusive radio buttons, not tick boxes? Should prevent >1 selected at a time
  # 🌱 Can we make a 'All data' option for 'Select data'? Options currently from global constants

  # Pre-populate the default list of columns for viewing
  observeEvent(input$search_box,
    {
      cols <- get_column_choices(input$search_box, constants)
      updateSelectInput(session,
        inputId = "SelectCol",
        choices = cols$all,
        selected = cols$default
      )
    },
    ignoreNULL = FALSE
  )

  # Generate a table for viewing
  output$search_table <- renderDT(
    {
      report_cols(
        search_tables = input$search_box,
        table_mapping = table_mapping,
        select_cols = input$SelectCol,
        special_need = input$search_sp_need,
        constants = constants
      )
    },
    rownames = FALSE,
    options = list(search = list(regex = TRUE)),
    filter = list(position = "top", clear = FALSE, plain = TRUE)
  )

  # Make a proxy table for display
  search_proxy <- dataTableProxy("search_table")

  # Edit tab ============================
  # Used to edit samples across Data Tables
  # Safest way to edit samples once they've been uploaded into Aurora
  # See Bulk edit tab for editing many samples

  # Render editable table
  output$tbl <- renderDT({
    xdt <- get_edit_table(
      check_group = input$checkGroup,
      table_mapping = table_mapping,
      duplicate_mode = input$DuplicateMode
    )

    datatable(
      data = xdt,
      selection = "multiple",
      rownames = FALSE,
      editable = TRUE,
      options = list(search = list(regex = TRUE))
    )
  })

  # DataTable proxy
  tblproxy <- dataTableProxy("tbl")

  # Add rows
  observeEvent(input$addRowEdit, {
    s <- input$tbl_rows_selected
    if (length(s)) {
      add_rows_to_edit_table(
        check_group = input$checkGroup,
        table_mapping = table_mapping,
        selected_rows = s,
        dup_count = input$dupRowEdit,
        proxy = tblproxy
      )
    } else {
      toastr_warning("Select a row!", position = "bottom-left")
    }
  })

  # Abandon rows
  observeEvent(input$AbandonEdit, {
    s <- input$tbl_rows_selected
    if (length(s)) {
      abandon_rows(
        check_group = input$checkGroup,
        table_mapping = table_mapping,
        selected_rows = s,
        proxy = tblproxy,
        abandon_enabled = input$abandonlive,
        save_fn = function() save_edits(input$checkGroup, table_mapping, fpath)
      )
    }
  })

  # Cell editing
  observeEvent(input$tbl_cell_edit, {
    xdt <- get(table_mapping[input$checkGroup], envir = .GlobalEnv)
    xdt <- editData(xdt, input$tbl_cell_edit, "tbl", rownames = FALSE)
    assign(table_mapping[input$checkGroup], xdt, envir = .GlobalEnv)
  })

  # Save edits
  observeEvent(input$SaveEdit, {
    save_edits(input$checkGroup, table_mapping, fpath)
  })

  # Batch edit tab ====
  observeEvent(input$bulk_table, {
    
    df <- get(table_mapping[input$bulk_table], envir = .GlobalEnv)
    
    match_cols <- get_matchable_columns(df, protected_columns)
    edit_cols  <- get_editable_columns(df, protected_columns)
    
    updateSelectInput(
      session,
      "bulk_match_col",
      choices = match_cols
    )
    
    updateSelectInput(
      session,
      "bulk_edit_col",
      choices = edit_cols
    )
    
  })
  
  
  observeEvent(input$bulk_match_col, {
    
    req(input$bulk_table)
    
    df <- get(table_mapping[input$bulk_table], envir = .GlobalEnv)
    
    vals <- sort(unique(df[[input$bulk_match_col]]))
    
    updateSelectInput(
      session,
      "bulk_match_val",
      choices = vals
    )
    
  })
  
  
  observeEvent(input$bulk_preview, {
    
    req(
      input$bulk_table,
      input$bulk_match_col,
      input$bulk_match_val,
      input$bulk_edit_col
    )
    
    df <- get(table_mapping[input$bulk_table], envir = .GlobalEnv)
    
    result <- bulk_preview_edit(
      df,
      input$bulk_match_col,
      input$bulk_match_val,
      input$bulk_edit_col,
      input$bulk_new_val
    )
    
    output$bulk_rows_changed <- renderText({
      paste("Rows affected:", result$rows_changed)
    })
    
    output$bulk_preview_table <- DT::renderDataTable({
      
      DT::datatable(
        result$preview,
        options = list(pageLength = 20, scrollX = TRUE)
      )
      
    })
    
  })
  
  
  observeEvent(input$bulk_apply, {
    
    req(
      input$bulk_table,
      input$bulk_match_col,
      input$bulk_match_val,
      input$bulk_edit_col
    )
    
    df <- get(table_mapping[input$bulk_table], envir = .GlobalEnv)
    
    df <- bulk_apply_edit(
      df,
      input$bulk_match_col,
      input$bulk_match_val,
      input$bulk_edit_col,
      input$bulk_new_val
    )
    
    table_key <- table_mapping[input$bulk_table]
    
    assign(table_key, df, envir = .GlobalEnv)
    
    saveRDS(
      df,
      file = paste0(fpath(), table_key, ".rds")
    )
    
    toastr_success("Bulk edit applied", position = "bottom-left")
    
  })
  

  # Move boxes tab ============================
  # Used for moving or renaming boxes
  # 🌱 Can we update this tab to handle both samples and extractions (as done for Check Boxes)?
  # 🌱 Can we combine the Check and Move boxes tabs?
  # 🌱 Could 'generate data' button to cope with refreshing data?
  # 🌱 Could moving tasks to a function .R file help with refreshing and changing sample type?
  observeEvent(input$moveBoxtoSubunit, {
    box_type <- input$data_type_move
    table_data <- update_storage_data(box_type)
    table_data[which(table_data$storage_box == as.character(input$moveBoxSelect)), "storage_shelf"] <<- as.character(input$movesubunitdest)
    values$subunitChoices_samples <<- levels(as.factor(table_data$storage_shelf))
    saveRDS(table_data, file = paste0(fpath, "table_storage_data.rds"))
    toastr_success("Records Updated", position = "bottom-left")
  })

  observeEvent(input$moveRenameBox, {
    box_type <- input$data_type_move
    table_data <- update_storage_data(box_type)
    table_data[which(table_data$storage_box == as.character(input$moveBoxSelect2)), "storage_box"] <<- as.character(input$moveBoxRename)
    values$boxChoices_samples <<- levels(as.factor(table_data$storage_box))
    saveRDS(table_data, file = paste0(fpath, "table_storage_data.rds"))
    toastr_success("Records Updated", position = "bottom-left")
  })

  observeEvent(input$moveRenameSubunit, {
    box_type <- input$data_type_move
    table_data <- update_storage_data(box_type)
    table_data[which(table_data$storage_box == as.character(input$moveSubunitSelect)), "storage_shelf"] <<- as.character(input$movesubunitRename)
    values$subunitChoices_samples <<- levels(as.factor(table_data$storage_box))
    saveRDS(table_data, file = paste0(fpath, "table_storage_data.rds"))
    toastr_success("Records Updated", position = "bottom-left")
  })

  # Upload tab ============================
  # Used to upload data from the aurora_queue.xlsx Excel file'Upload' tab
  # This is the safest way to upload many samples, as the upload functions do many formatting checks

  observeEvent(input$Upload, {
    print("Importing new samples...")

    upload_new_samples(
      constants = constants,
      table_mapping = table_mapping,
      fpath = fpath # Pass the reactive itself, not fpath()
    )
  })

  # Export tab ============================
  # Used to export samples (or other data) in various formats
  # This is for data export - for reports, see Report tab

  export_data <- reactiveValues(df = NULL)

  # Generate export dataset
  observeEvent(input$generateData, {
    toastr_warning("Generating data", position = "bottom-left")

    export_data$df <- generate_export_data()

    toastr_success("Data generated", position = "bottom-left")
  })

  # Export all samples
  observeEvent(input$exportSamples, {
    if (is.null(export_data$df)) {
      toastr_error("No data available. Please generate data first.", position = "bottom-left")
      return()
    }

    toastr_warning("Exporting all samples", position = "bottom-left")
    export_dataset(export_data$df, "all_samples")
    toastr_success("Saved to Export folder", position = "bottom-left")
  })

  # Export sequenced samples
  observeEvent(input$exportSequenced, {
    if (is.null(export_data$df)) {
      toastr_error("No data available. Please generate data first.", position = "bottom-left")
      return()
    }

    toastr_warning("Exporting sequenced samples", position = "bottom-left")
    filtered_df <- filter_sequenced_samples(export_data$df)
    export_dataset(filtered_df, "sequenced_samples")
    toastr_success("Saved to Export folder", position = "bottom-left")
  })

  # 🌱 Need to make these new output formats
  # Export all sequenced samples for GenBank (.xlsx)
  # exportGenBank



  # Bulk edit tab ============================
  # Used to export and import each Data Table .rds file for manual bulk editing in Excel or a text editor
  # See Edit tab for editing smaller numbers of samples more safely

  observeEvent(input$UtilsExport, {
    toastr_warning("Export Underway...", position = "bottom-left")
    bulk_export_table(input$UtilscheckGroup, fpath, examplepath)
    toastr_success("Exported", position = "bottom-left")
  })

  observeEvent(input$UtilsImport, {
    if (input$UtilsConfirm == TRUE) {
      toastr_warning("Import Underway...", position = "bottom-left")
      success <- bulk_import_table(input$UtilscheckGroup, fpath, mungepath, examplepath)

      if (success) {
        toastr_success("Imported", position = "bottom-left")
      }
    } else {
      toastr_warning("Select Table; Enable Import!", position = "bottom-left")
    }
  })

  # Dashboard tab ============================
  # Used to evaluate statistics tracking the Aurora database
  # i.e. how many samples (and other data) stored in the Aurora database
  # Can use plots to identify if significant uploads or deletions have occurred

  # Reactive value to store dashboard_data
  dashboard_data <- reactiveVal(NULL)

  # Generate data on button press
  observeEvent(input$generate_dashboard, {
    dashboard_data(generate_dashboard_data())
  })

  # Ensure there's initial data
  observe({
    if (is.null(dashboard_data())) {
      dashboard_data(generate_dashboard_data())
    }
  })

  # Timeline plot
  output$accumulation_plot <- renderPlotly({
    req(dashboard_data())
    generate_accumulation_plot(dashboard_data())
  })

  # Tracker plot
  output$tableTally1 <- renderPlotly({
    generate_tracker_plot(table_Tracker)
  })

  # Index purity table
  output$uniques.Taxonomy <- renderTable({
    generate_index_purity_table()
  })


  # Filter tab  ============================
  # Used to prepare and filter data (i.e. generates report_data)
  # report_data then used by storage, diversity, geography, timeline and report tabs

  report_data <- reactiveValues(df = NULL)

  values$reportFilterColumns <- c(
    "project", "project_code", "key_word",
    "family", "genus", "species_binomial",
    "storage_unit", "storage_box", "extract_unit", "extract_box",
    "sample_trip",
    "political_country", "political_state", "geographic_region", "geographic_subregion",
    "sequencing_run", "key_publication"
  )

  # Generate base dataset
  observeEvent(input$generateReportData, {
    toastr_warning("Generating data", position = "bottom-left")

    # Unified dataset generator — uses date-safe joins
    new_data <- generate_export_data()

    # Save to reactiveValues and global for reuse
    report_data$df <- new_data
    assign("report_data", report_data$df, envir = .GlobalEnv)

    toastr_success("Data generated", position = "bottom-left")
  })

  # Dynamic filter UI
  output$multi_filter_ui <- renderUI({
    req(report_data$df)

    tagList(
      h4("Filter by:"),
      lapply(values$reportFilterColumns, function(col) {
        choices <- get_report_filter_choices(report_data$df, col)
        pickerInput(
          inputId = paste0("filter_", col),
          label = gsub("_", " ", toTitleCase(col)),
          choices = choices,
          options = list(`actions-box` = TRUE, `live-search` = TRUE),
          multiple = TRUE
        )
      }),
      actionButton("resetAllFilters", "Clear all filters", icon = icon("undo"), class = "btn-warning w-100")
    )
  })

  # Filtering logic
  filtered_df <- reactive({
    req(report_data$df)
    df <- report_data$df

    # Loop over all filter inputs dynamically
    for (col in values$reportFilterColumns) {
      input_id <- paste0("filter_", col)
      vals <- input[[input_id]]
      if (!is.null(vals) && !("All" %in% vals) && length(vals) > 0) {
        df <- df[df[[col]] %in% vals, , drop = FALSE]
      }
    }

    assign("report_data", df, envir = .GlobalEnv)
    df
  })

  # Reset filters
  observeEvent(input$resetAllFilters, {
    lapply(values$reportFilterColumns, function(col) {
      updatePickerInput(session, paste0("filter_", col), selected = character(0))
    })
    assign("report_data", report_data$df, envir = .GlobalEnv)
    toastr_info("All filters cleared — showing all data", position = "bottom-left")
  })

  # Add filtered data to reportItems for export
  observe({
    req(filtered_df())
    reportItems$tables[["All sample data"]] <- filtered_df()
  })

  # Table display
  output$report_filtered_table <- renderDT({
    req(filtered_df())
    datatable(
      filtered_df(),
      options = list(pageLength = 10, scrollX = TRUE),
      caption = "All sample data"
    )
  })

  # Storage tab ==================================
  # Used to visualise and assess the storage of samples and extractions in report_data
  # e.g. where are a project's samples kept, or what is stored in a particular freezer

  # Reactive value to store storage_data
  storage_data <- reactiveVal(NULL)

  # Refresh Button
  observeEvent(input$refresh_storage, {
    if (exists("report_data", envir = .GlobalEnv)) {
      new_data <- get("report_data", envir = .GlobalEnv)
      storage_data(new_data)
      showNotification("Storage data refreshed", type = "message")
    } else {
      showNotification("No report data found. Please generate it first in the Filter tab.", type = "error")
    }
  })

  # Generate Figures + Tables
  observeEvent(input$generate_all_figs, {
    dat <- storage_data()
    req(dat) # Require data before proceeding

    # Sample storage table
    # Lists unique boxes per sample storage unit
    sample_table <- dat %>%
      filter(!is.na(storage_unit) | !is.na(storage_box)) %>%
      group_by(storage_unit, storage_box) %>%
      summarise(
        Unique_Samples = n_distinct(sample_accession),
        .groups = "drop"
      ) %>%
      filter(!is.na(storage_unit) & !is.na(storage_box))

    output$sample_storage_table <- renderDT({
      datatable(
        sample_table,
        rownames = FALSE,
        caption = "Unique Storage Boxes by Unit (Samples)",
        options = list(pageLength = 10, dom = "tip")
      )
    })
    reportItems$tables$sample_storage_table <- sample_table


    # Extraction storage table
    # Lists unique boxes per extract storage unit
    extract_table <- dat %>%
      filter(!is.na(extract_unit) | !is.na(extract_box)) %>%
      group_by(extract_unit, extract_box) %>%
      summarise(
        Unique_Extractions = n_distinct(extract_accession),
        .groups = "drop"
      ) %>%
      filter(!is.na(extract_unit) & !is.na(extract_box))

    output$extract_storage_table <- renderDT({
      datatable(
        extract_table,
        rownames = FALSE,
        caption = "Unique Extraction Boxes by Unit (Extractions)",
        options = list(pageLength = 10, dom = "tip")
      )
    })
    reportItems$tables$extract_storage_table <- extract_table

    # Sample Inventory Table
    # Lists storage information for every sample within report_data
    sample_inventory_cols <- c(
      "sample_accession", "storage_unit", "storage_shelf", "storage_rack",
      "storage_slot", "storage_box", "storage_plate", "storage_well",
      "storage_date", "sample_status", "storage_note", "storage_label"
    )

    sample_inventory <- dat %>%
      filter(!is.na(storage_unit) | !is.na(storage_box)) %>%
      select(all_of(sample_inventory_cols)) %>%
      distinct() # Ensure unique rows per sample storage record

    output$sample_inventory <- renderDT({
      datatable(
        sample_inventory,
        rownames = FALSE,
        caption = "Detailed Sample Storage Inventory",
        options = list(pageLength = 10, scrollX = TRUE)
      )
    })
    reportItems$tables$sample_inventory <- sample_inventory


    # Extraction Inventory Table
    # Lists storage information for every extraction within report_data
    extract_inventory_cols <- c(
      "sample_accession", "extract_accession", "extract_unit", "extract_shelf",
      "extract_rack", "extract_slot", "extract_box", "extract_plate",
      "extract_well", "extract_date", "extract_status", "extract_storage_note"
    )

    extract_inventory <- dat %>%
      filter(!is.na(extract_unit) | !is.na(extract_box)) %>%
      select(all_of(extract_inventory_cols)) %>%
      distinct() # Ensure unique rows per extraction storage record

    output$extract_inventory <- renderDT({
      datatable(
        extract_inventory,
        rownames = FALSE,
        caption = "Detailed Extraction Storage Inventory",
        options = list(pageLength = 10, scrollX = TRUE)
      )
    })
    reportItems$tables$extract_inventory <- extract_inventory

    # Sample storage figures
    samples <- dat %>%
      filter(!is.na(storage_unit) | !is.na(storage_box)) %>%
      select(
        sample_accession, project, storage_unit, storage_shelf,
        storage_rack, storage_slot, storage_box
      )

    p_sample_hist <- make_storage_histogram(
      samples, "storage_unit", "project",
      "Storage Unit", "Number of Samples"
    )
    output$sample_hist <- renderPlotly({
      p_sample_hist
    })
    reportItems$plots$sample_hist <- p_sample_hist

    p_sample_sankey <- make_storage_sankey(
      data = samples,
      level1 = "storage_unit", level2 = "storage_shelf",
      level3 = "storage_rack", level4 = "storage_box"
    )
    output$sample_sankey <- renderPlotly({
      p_sample_sankey
    })
    reportItems$plots$sample_sankey <- p_sample_sankey


    # Extraction storage figures
    extracts <- dat %>%
      filter(!is.na(extract_unit) | !is.na(extract_box)) %>%
      select(
        extract_accession, project, extract_unit, extract_shelf,
        extract_rack, extract_slot, extract_box
      )

    p_extract_hist <- make_storage_histogram(
      extracts, "extract_unit", "project",
      "Extraction Unit", "Number of Extractions"
    )
    output$extract_hist <- renderPlotly({
      p_extract_hist
    })
    reportItems$plots$extract_hist <- p_extract_hist

    p_extract_sankey <- make_storage_sankey(
      data = extracts,
      level1 = "extract_unit", level2 = "extract_shelf",
      level3 = "extract_rack", level4 = "extract_box"
    )
    output$extract_sankey <- renderPlotly({
      p_extract_sankey
    })
    reportItems$plots$extract_sankey <- p_extract_sankey

    # Notification
    showNotification("All storage plots and tables generated successfully", type = "message")
  })


  # Diversity tab =========================================
  # Used to assess the taxonomic diversity of samples in report_data

  # Reactive value to store diversity_data
  diversity_data <- reactiveVal(NULL)

  # Check if report_data is present
  observeEvent(input$refresh_diversity, {
    if (exists("report_data", envir = .GlobalEnv)) {
      diversity_data(get("report_data", envir = .GlobalEnv))
      showNotification("Loaded data from Filter tab", type = "message")
    } else {
      showNotification("No data found. Please generate data first in the Filter tab", type = "error")
    }
  })

  observeEvent(input$generate_diversity_plot, {
    dat <- diversity_data()
    req(dat, input$x_tax_level, input$color_tax_level)

    if (input$x_tax_level == input$color_tax_level) {
      showNotification(
        "Please select two different taxonomic levels to compare",
        type = "error",
        duration = 5
      )
      return(NULL)
    }

    # Generate outputs using helper functions
    diversity_summary <- generate_diversity_summary(dat, input$x_tax_level, input$color_tax_level)
    plt <- generate_diversity_histogram(dat, input$x_tax_level, input$color_tax_level)

    # Render and store results
    output$diversity_summary_table <- renderDataTable({
      datatable(diversity_summary, options = list(pageLength = 10), rownames = FALSE)
    })
    output$diversity_plot <- renderPlotly({
      plt
    })

    # Add to reportItems for export
    reportItems$tables$diversity_summary <- diversity_summary
    reportItems$plots$diversity_histogram <- plt
  })


  # Geography tab =========================================
  # Used to map and assess the spatial distribution of samples in report_data

  # Reactive value to store map data
  map_data_reactive <- reactiveVal(NULL)

  # Refresh map data
  observeEvent(input$generate_data, {
    req(filtered_df()) # Ensure filtered data exists

    map_data <- prepare_map_data(filtered_df()) # Prepare map data from filtered data

    map_data_reactive(map_data)
    showNotification("Map data refreshed", type = "message")
  })

  # Generate map and geography summary table
  observeEvent(input$generate_map, {
    map_data <- map_data_reactive()

    basemap_selected <- input$basemap_choice

    # Validate that map data exists
    if (is.null(map_data) || nrow(map_data) == 0) {
      showNotification("No map data available to display", type = "error")
      output$map_samples <- renderLeaflet({
        leaflet() %>%
          addProviderTiles(providers$Esri.WorldTopoMap) %>%
          setView(lng = 0, lat = 0, zoom = 2)
      })
      output$geography_summary_table <- renderDataTable({
        datatable(data.frame(Message = "No map data available"), options = list(dom = "t"))
      })
      return()
    }

    # If either coordinate column has entirely no data, stop and show error
    if (all(is.na(map_data$lat1)) || all(is.na(map_data$long1))) {
      showNotification("No coordinate data available for map", type = "error")
      output$map_samples <- renderLeaflet({
        leaflet() %>%
          addProviderTiles(providers$Esri.WorldTopoMap) %>%
          setView(lng = 0, lat = 0, zoom = 2)
      })
      output$geography_summary_table <- renderDataTable({
        datatable(data.frame(Message = "No coordinate data available"), options = list(dom = "t"))
      })
      return()
    }

    # Otherwise, render the map (even if some rows have missing coordinates)
    output$map_samples <- renderLeaflet({
      rendermap(map_data, basemap_selected)
    })

    # Store rendered map for reporting
    reportItems$plots$sample_map <- rendermap(map_data, basemap_selected)

    # Generate summary table for map data
    geography_summary <- map_data %>%
      group_by(
        political_country,
        political_state,
        geographic_region,
        geographic_subregion,
        sample_location,
        sample_point
      ) %>%
      summarise(
        n_samples = n(),
        .groups = "drop"
      ) %>%
      arrange(desc(n_samples))

    # Render the summary table
    output$geography_summary_table <- renderDataTable({
      datatable(
        geography_summary,
        options = list(
          pageLength = 10,
          order = list(list(6, "desc"))
        ),
        rownames = FALSE
      )
    })

    # Store table for reporting
    reportItems$tables$geography_summary <- geography_summary

    showNotification("Map and summary table generated.", type = "message")
  })

  output$map_samples <- renderLeaflet({
    leaflet() %>%
      addProviderTiles(providers$Esri.WorldTopoMap) %>%
      setView(lng = 0, lat = 0, zoom = 2)
  })

  # Timeline tab =========================================
  # Used to assess temporal variation for samples in report_data
  # Accumulation plots show the accumulation of data across the dated data tables over time
  # i.e. how many samples collected, stored, extracted, library prepared, and sequenced
  # Process plots show dated information per sample
  # i.e. shows how long for a sample to be collected, stored, extracted, library prepared, and sequenced

  # Reactive value to store timneline data
  timeline_data <- reactiveVal(NULL)

  # Refresh Button
  observeEvent(input$refresh_timeline, {
    if (exists("report_data", envir = .GlobalEnv)) {
      new_data <- get("report_data", envir = .GlobalEnv)
      timeline_data(new_data)
      showNotification("Report data loaded successfully", type = "message")
    } else {
      showNotification("No report data found. Please generate report data on Filter tab", type = "error")
    }
  })

  # Generate Tables and Figures
  observeEvent(input$generate_timeline, {
    req(timeline_data())

    showNotification("Generating timeline figures...", type = "message")

    tryCatch(
      {
        # Generate timeline accumulation plot
        data_list <- generate_timeline_dashboard_data(timeline_data())
        timeline_accumulation_plot <- generate_timeline_accumulation_plot(data_list)
        output$timeline_accumulation_plot <- renderPlotly({
          timeline_accumulation_plot
        })

        # Generate sample processing timeline plot
        process_data <- generate_timeline_process_data(timeline_data())
        timeline_process_plot <- generate_timeline_process_plot(process_data)
        output$timeline_process_plot <- renderPlotly({
          timeline_process_plot
        })

        # Add plots to reportItems
        reportItems$plots$timeline_accumulation_plot <- timeline_accumulation_plot
        reportItems$plots$timeline_process_plot <- timeline_process_plot

        showNotification("Timeline figures generated", type = "message")
      },
      error = function(e) {
        showNotification(
          paste("Error generating figures:", e$message),
          type = "error"
        )
      }
    )
  })

  
  # Report tab =========================================
  # Used to export reports using report_data
  # Reports can be interactive .html reports, Excel files or .html maps files
  # This is for exporting reports, for data export - see Export tab
  
  # UI Builders
  output$select_tables_ui <- renderUI({
    table_names <- names(reportItems$tables)
    if (length(table_names) == 0) {
      return(h6("No tables available yet"))
    }
    
    # Identify the 'All sample data' table
    all_sample_data_table <- "All sample data"
    
    # Get all table names EXCEPT 'All sample data'
    default_selected <- setdiff(table_names, all_sample_data_table)
    
    # Pre-select all tables except 'All sample data'
    checkboxGroupInput(
      "selected_tables", "Tables:",
      choices = table_names,
      selected = default_selected
    )
  })
  
  output$select_plots_ui <- renderUI({
    plot_names <- names(reportItems$plots)
    if (length(plot_names) == 0) {
      return(h6("No plots available yet"))
    }
    checkboxGroupInput(
      "selected_plots", "Plots:",
      choices = plot_names,
      selected = plot_names
    )
  })
  
  
  ## Preview UI ====
  # This UI provides a 'live preview' of tables and figures selected for export in reports
  output$report_preview_ui <- renderUI({
    preview_list <- list()
    
    # Preview tables
    if (!is.null(input$selected_tables) && length(input$selected_tables) > 0) {
      for (t in input$selected_tables) {
        if (is.null(reportItems$tables[[t]])) next
        
        safe_name <- gsub("\\W+", "_", t)
        out_id <- paste0("preview_table_", safe_name)
        
        local({
          tbl_name <- t
          oid <- out_id
          output[[oid]] <- renderDataTable({
            datatable(
              reportItems$tables[[tbl_name]],
              options = list(pageLength = 10, scrollX = TRUE),
              rownames = FALSE
            )
          })
        })
        
        preview_list <- append(
          preview_list,
          list(h5(strong(t)), dataTableOutput(out_id), tags$hr())
        )
      }
    }
    
    # Preview plots
    if (!is.null(input$selected_plots) && length(input$selected_plots) > 0) {
      for (p in input$selected_plots) {
        if (is.null(reportItems$plots[[p]])) next
        
        safe_name <- gsub("\\W+", "_", p)
        out_id <- paste0("preview_plot_", safe_name)
        
        local({
          plot_name <- p
          oid <- out_id
          plt_obj <- reportItems$plots[[plot_name]]
          
          if (inherits(plt_obj, "leaflet")) {
            output[[oid]] <- renderLeaflet({
              plt_obj
            })
          } else {
            output[[oid]] <- renderPlotly({
              plt_obj
            })
          }
        })
        
        # Determine plot titles for preview
        plot_title <- tryCatch(
          if (!is.null(reportItems$plots[[p]]$x$layout$title$text)) {
            reportItems$plots[[p]]$x$layout$title$text
          } else {
            p
          },
          error = function(e) p
        )
        
        # Determine UI output function
        plot_ui <- if (inherits(reportItems$plots[[p]], "leaflet")) {
          leafletOutput(out_id, height = "420px")
        } else {
          plotlyOutput(out_id, height = "420px")
        }
        
        preview_list <- append(
          preview_list,
          list(h5(strong(plot_title)), plot_ui, tags$hr())
        )
      }
    }
    
    if (length(preview_list) == 0) {
      preview_list <- list(h6("Select tables or plots to preview"))
    }
    
    do.call(tagList, preview_list)
  })
  
  
  ## Export hmtl report ====
  observeEvent(input$generate_report, {
    req(!is.null(input$selected_tables) ||
          !is.null(input$selected_plots))
    
    showNotification("Generating report... please wait", type = "message", duration = 5)
    
    # Ensure output folder exists
    if (!dir.exists(reportpath)) dir.create(reportpath, recursive = TRUE)
    
    timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
    report_date <- format(Sys.time(), "%d %B %Y, %H:%M")
    qmd_fname <- paste0("Aurora_Report_", timestamp, ".qmd")
    html_fname <- paste0("Aurora_Report_", timestamp, ".html")
    qmd_file <- file.path(reportpath, qmd_fname)
    
    # YAML header (using glue)
    yaml_header <- glue("
---
title: \"{input$report_title}\"
output: html_document
---

")
    
    content <- c(yaml_header,
                 glue("<strong>Date generated:</strong> {report_date}")
                 )
    assigned_globals <- character(0)
    
    # Tables
    if (!is.null(input$selected_tables) && length(input$selected_tables) > 0) {
      content <- c(content, "\n## Tables\n")
      
      i <- 0
      for (t in input$selected_tables) {
        df <- reportItems$tables[[t]]
        if (is.null(df)) next
        i <- i + 1
        
        obj_name <- paste0("tbl_", gsub("\\W+", "_", t))
        assign(obj_name, df, envir = globalenv())
        assigned_globals <- c(assigned_globals, obj_name)
        
        content <- c(
          content,
          glue("### {t}\n"),
          glue("```{{r, echo=FALSE}}\nDT::datatable({obj_name}, options = list(pageLength = 10, scrollX = TRUE))\n```\n")
        )
      }
    }
    
    # Plots
    if (!is.null(input$selected_plots) && length(input$selected_plots) > 0) {
      content <- c(content, "\n## Plots\n")
      
      for (p in input$selected_plots) {
        plt <- reportItems$plots[[p]]
        if (is.null(plt)) next
        
        plot_title <- tryCatch(
          if (!is.null(plt$x$layout$title$text)) {
            plt$x$layout$title$text
          } else {
            p
          },
          error = function(e) p
        )
        
        content <- c(content, glue("### {plot_title}\n"))
        
        # Assign all plots (Leaflet or Plotly) to a global variable
        obj_name <- paste0("plt_", gsub("\\W+", "_", p))
        assign(obj_name, plt, envir = globalenv())
        assigned_globals <- c(assigned_globals, obj_name)
        
        if (inherits(plt, "leaflet")) {
          # Render Leaflet directly (htmlwidget)
          # Includes warning=FALSE to prevent report including colour warning
          content <- c(
            content,
            glue("```{{r, echo=FALSE, fig.height=6, out.width='100%', warning=FALSE}}\n{obj_name}\n```\n")
          )
        } else {
          # Render Plotly
          # Includes warning=FALSE to prevent report including colour warning
          content <- c(
            content,
            glue("```{{r, echo=FALSE, warning=FALSE, out.width='100%'}}\nplotly::plotly_build({obj_name})\n```\n")
          )
        }
      }
    }
    
    # Add acknowledgements section
    content <- c(
      content,
      "<strong>This report was generated using Aurora</strong>.
      <br />Please cite: Zareie-Vaux F., Abernethy G.A. 2026. Aurora: a versatile, open-source laboratory information management system for biological samples using R Shiny. <i>Journal of Open Source Software</i>, XX, XX-XX. <a href='https://www.doi.org/'>DOI.XXX.XXXX</a>"
    )
    
    # Write temporary qmd file
    writeLines(content, qmd_file)
    
    # Render with rmarkdown in-session
    tryCatch({
      render(
        input = qmd_file,
        output_file = html_fname,
        output_dir = reportpath,
        envir = globalenv(),
        quiet = TRUE
      )
      
      final_path <- file.path(reportpath, html_fname)
      showNotification("Report successfully generated!", type = "success", duration = 5)
      browseURL(final_path)
    }, error = function(e) {
      showNotification(paste("Error generating report:", e$message), type = "error", duration = NULL)
    }, finally = {
      # Clean up global environment variables
      try(
        {
          if (length(assigned_globals) > 0) {
            rm(list = assigned_globals, envir = globalenv())
          }
        },
        silent = TRUE
      )
    })
  })
  
  ## Export Excel ====
  observeEvent(input$export_selected_tables, {
    selected_table_names <- input$selected_tables
    
    if (is.null(selected_table_names) || length(selected_table_names) == 0) {
      showNotification("No tables selected for export", type = "warning", duration = 5)
      return()
    }
    
    showNotification("Exporting tables to Excel... please wait", type = "message", duration = 5)
    
    tryCatch(
      {
        # Ensure output folder exists
        if (!dir.exists(reportpath)) dir.create(reportpath, recursive = TRUE)
        
        # Define the full file path inside the reportpath directory
        timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
        excel_fname <- paste0("Selected_Tables_Export_", timestamp, ".xlsx")
        final_path <- file.path(reportpath, excel_fname)
        
        # Extract the actual data frames based on selected names
        table_list <- reportItems$tables[selected_table_names]
        names(table_list) <- selected_table_names # Use table names as sheet names
        
        # Write the data frames to the Excel file on the server
        write_xlsx(table_list, path = final_path)
        
        # Notify the user and open the folder
        showNotification(
          paste(length(selected_table_names), "tables exported to:", final_path),
          type = "message",
          duration = 10
        )
      },
      error = function(e) {
        showNotification(paste("Error exporting Excel:", e$message), type = "error", duration = NULL)
      }
    )
  })
  
  ## Export map ====
  observeEvent(input$export_report_map, {
    # Check for map data
    map_to_save <- reportItems$plots$sample_map
    
    if (is.null(map_to_save) || !inherits(map_to_save, "leaflet")) {
      showNotification("Map data is not available. Please generate the map first",
                       type = "warning", duration = 5
      )
      return()
    }
    
    showNotification("Exporting map to HTML... please wait", type = "message", duration = 5)
    
    tryCatch(
      {
        # Ensure output folder exists
        if (!dir.exists(reportpath)) dir.create(reportpath, recursive = TRUE)
        
        # Define the full file path inside the reportpath directory
        timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
        html_fname <- paste0("Map_Export_", timestamp, ".html")
        final_path <- file.path(reportpath, html_fname)
        
        # Save the leaflet map widget directly to the final path
        saveWidget(map_to_save, file = final_path, selfcontained = TRUE)
        
        # Notify the user of successful export
        showNotification(
          paste("Map exported successfully to:", final_path),
          type = "success",
          duration = 8
        )
      },
      error = function(e) {
        showNotification(paste("Error exporting map:", e$message), type = "error", duration = NULL)
      }
    )
  })

  # END ============================
} # end of server
